server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**
    upload-service: /upload/** # 将上传文件微服务映射到/upload/**
    search-service: /search/** # 将搜索微服务映射到/search/**
    user-service: /user/** # 将用户微服务映射到/user/**
    auth-service: /auth/** # 授权中心微服务

  ignored-patterns: /**/upload/** #禁用某个路由 上传服务绕过网关，IO操作耗时耗资源，避免阻塞
  add-host-header: true # 携带请求本身的Head头信息
  sensitive-headers: # 配置禁止使用的头信息，sensitiveHeaders去掉了默认的"Cookie", "Set-Cookie"
    - Authorization

ribbon:
  ConnectTimeout: 2500 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 100000 # 熔断超时时长：10000ms
ego:
  jwt:
    pubKeyPath: D:\\JavaStudy\\Course3\\7-ego\\temp\\rsa.pub # 公钥地址
    cookieName: EGO_TOKEN # cookie的名称
  filter:
    allowPaths: #拦截白名单
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/send
      - /api/item