server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.30.128
    username: ego
    password: ego
    virtual-host: /ego
    listener:
      simple:
        #消费者报错，自动重试
        retry:
          ####开启消费者重试
          enabled: true
          ####最大重试次数(3次)
          max-attempts: 5
          ####重试间隔(毫秒)
          initial-interval: 1
        ####开启手动ack
        acknowledge-mode: manual
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15