server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ego
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.30.128
  rabbitmq:
    host: 192.168.30.128
    username: ego
    password: ego
    virtual-host: /ego
    template:
      exchange: ego.sms.exchange # 缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 210000ms
        multiplier: 2
    publisher-confirms: true
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
# Mybatis
mybatis:
  type-aliases-package: com.ego.user.pojo
