server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/ego
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
    host: 192.168.30.128 # RabbitMQ地址
    username: ego # RabbitMQ用户名
    password: ego # RabbitMQ密码
    virtual-host: /ego  # RabbitMQ虚拟主机名
    template:
      exchange: ego.item.exchange # 缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
      retry:
        enabled: false #失败重试(暂时关闭)
    publisher-confirms: true # 生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  configuration:
    log-impl:
      org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.ego.item.pojo       #pojo别名
# mapper-locations: com.ego.item.mapper/*.xml